typedef struct Node *Lligada;
char* getLinha(Lligada a);
float getData(Lligada a);
Lligada getNext(Lligada a);
float maxLligada(Lligada a, int k);
float getKdata(Lligada a, int k);
void swapNodes(Lligada *headr, float key1, float key2);
void push(Lligada* head_ref, float new_data, char* produto);
void MergeSort(Lligada* headRef);
void printList(struct Node *node);
void printNList(Lligada node, int k);